language: python
os:
  - linux
  - osx


sudo: false
dist: trusty

git:
  depth: 1

branches:
  only:
  - master

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi
  - pip install cram

script:
  - echo Hello World