os: linux
dist: trusty
language: python
python: "3.6"
sudo: false

git:
  depth: 1

branches:
  only:
  - master

install:
- ./.ci/install-deps.sh

script:
- shellcheck src/*.m4
- cram -v -q test/*.t

after_failure:
- cat test/*.err
