language: python

matrix:
  include:
  - os: linux
    python: "3.6"
  - os: osx
    language: generic

sudo: false
dist: trusty

git:
  depth: 1

branches:
  only:
  - master

install:
- pip install cram

script:
- echo Hello World