language: python
python:
  - "3.6"
os:
  - linux
  - osx

matrix:
  include:
    - python: "3.6"
      os: linux
    - os: osx

sudo: false
dist: trusty

git:
  depth: 1

branches:
  only:
  - master

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi

install:
- pip install cram

script:
  - echo Hello World