os: linux
dist: trusty
language: python
python: "3.6"
sudo: true

git:
  depth: 1

install:
- ./.ci/install-deps.sh

script:
- ./.ci/build.sh
- shellcheck bin/*
- (cram -v test/*.t > test/test.log && cat test/test.log | tail -n 1) || (cat test/test.log | tail -n 1 && false)

after_failure:
- cat test/test.log
