matrix:
  include:
  - os: linux
    language: python
    python: "3.6"
    sudo: false
    dist: trusty
  - os: osx
    language: generic

git:
  depth: 1

branches:
  only:
  - master

install:
- pip install cram

script:
- echo Hello World