language: sh
os:
  - linux
  - osx


sudo: required
dist: trusty

git:
  depth: 1

branches:
  only:
  - master

services:
  - docker

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi
  - mkdir -p $TRAVIS_BUILD_DIR/.build/bin
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -o $TRAVIS_BUILD_DIR/.build/bin/container-structure-test https://storage.googleapis.com/container-structure-test/latest/container-structure-test-darwin-amd64; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -o $TRAVIS_BUILD_DIR/.build/bin/container-structure-test https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64; fi
  - chmod +x $TRAVIS_BUILD_DIR/.build/bin/container-structure-test
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/.build/bin

script:
  - echo Hello World