os: linux
dist: trusty
language: python
python: "3.6"
sudo: false

git:
  depth: 1

install:
- ./.ci/install-deps.sh

script:
- ./.ci/build.sh
- shellcheck bin/*
- cram -v test/*.t > test/log.txt || (cat test/log.txt | tail -n 1 && false)

after_failure:
- cat test/log.txt
