# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        ./.ci/install-deps.sh
    - name: Build
      run: |
        ./.ci/build.sh
    - name: Check
      run: |
        shellcheck bin/*
    - name: Test
      run: |
        (cram -v test/*.t > test/test.log && cat test/test.log | tail -n 1) || (cat test/test.log | tail -n 1 && false)
    - name: Print logs on fail
      if: ${{ failure() }}
      run: |
        cat test/test.log
