name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        ./.ci/install-deps.sh
    - name: Build
      run: |
        pipenv run .ci/build.sh
    - name: Check
      run: |
        shellcheck bin/*
    - name: Test
      run: |
        (pipenv run cram -v test/*.t > test/test.log && cat test/test.log | tail -n 1) || (cat test/test.log | tail -n 1 && false)
    - name: Print logs on fail
      if: ${{ failure() }}
      run: |
        cat test/test.log
